### ISSUE TITLE
[BUG] batching does not batch

### ISSUE THREAD

**Issue by yuvalgut** [streamnative/pulsar-io-cloud-storage#12]
**Describe the bug**
While configuring s3 parquet sink with batching, I find out that the sinks creates a separate file for each record.

**To Reproduce**
1. create a parquet/avro s3 sink with batching 
2. send 2 messages
3. see that there are 2 parquet files on s3

**Expected behavior**
1 file parquet file containing 2 records

**Proposed solution**
from the code it seems that the batching is done wrong. we should batch 'plain' GenericRecords on the 'write' function, and later on the 'flush' function we should group records with by schema and partition path, change the 'Format.recordWriter' to take a list of records and only then send it to the blob store.

Side note:
In general a lot of sinks need some kind of windowing, is there any way to configure the window properties of pulsar function to work with pulsar sink? I think it could be useful to have another api for the sink that would get a collection of records rather than 1 record at a time. this way we do not need to reimplement batching for each sink

EDIT: is there a way to open PR with a fix?

@codelipenghui @jianyun8023

**Comment by jianyun8023** [comment]
This is my design gone wrong and your expectations are right. This is an issue I will fix it next as soon as possible.
This is a connector when open source, everyone can submit pr to improve it.
Your participation is very welcome.
