### ISSUE TITLE
Release Cloud IO connector in streamnative-ci

### ISSUE THREAD

**Issue by timmyyuan** [streamnative/pulsar-io-cloud-storage#13]
According to https://github.com/streamnative/streamnative-ci/issues/374, Cloud IO connector will be included in streamnative-ci and appear in sn-pulsar and cloud pulsar images. The release process of Cloud IO connector can refer to the plugin part (e.g. Aop and Kop) in [StreamNative Weekly Release Process](https://streamnative.slab.com/posts/stream-native-weekly-release-process-fta1dvcm). There are two things that need to be confirmed:

**1. `set-pulsar-version.sh` and `set-project-version.sh`**
Are there any other scripts (similar in function to `set-pulsar-version.sh` and `set-project-version.sh`) to adjust the pulsar version it depends on, and how to use them?

**2. Create a project directory under the `streamnative-ci/projects/`**
Please submit a project directory to [streamnative-ci/projects](https://github.com/streamnative/streamnative-ci/tree/master/projects). In general, under the submitted project, there should be three shell scripts, i.e. `build.sh`, `get-version.sh` and `set-version.sh`. To add this directory, You can refer to [this document](https://github.com/streamnative/streamnative-ci/blob/master/doc/how-to-add-release-project-process.md) and the directories submitted by other projects in `streamnative-ci/projects`

Please contact me if you have any question :)

**Comment by jianyun8023** [comment]
Item 2: https://github.com/streamnative/streamnative-ci/pull/476
