### ISSUE TITLE
[BUG] Impossible to select the partition type

### ISSUE THREAD

**Issue by Damien137** [streamnative/pulsar-io-cloud-storage#19]
Between the two `partitionerType`: partition (default) and time, it is not possible to use partition.

This is due to the fact that is a mismatch in the code. The `partitionerType` is [defined with the types](https://github.com/streamnative/pulsar-io-cloud-storage/blob/3c734a592598f04a012cfaea0d808907fc5d44d7/src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java#L64): `default` and `time`. With the [condition below](https://github.com/streamnative/pulsar-io-cloud-storage/blob/3c734a592598f04a012cfaea0d808907fc5d44d7/src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java#L97), the property has to contain one of the two defined values.

Then the types `partition` [is used instead of](https://github.com/streamnative/pulsar-io-cloud-storage/blob/3c734a592598f04a012cfaea0d808907fc5d44d7/src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java#L110) `default`, therefore we can't use it.

Two possibilities to revolve the mismatch:
- Rename `default` by `partition` in the Map, to be aligned with the documentation.
- Rename `partition` by `default` in the switch and update the documentation.

**Comment by jianyun8023** [comment]
@freeznet Sorry, I haven't dealt with this issue, it needs you to solve it.

**Comment by freeznet** [comment]
fixed by https://github.com/streamnative/pulsar-io-cloud-storage/pull/146
