### ISSUE TITLE
[BUG] Verify the connector can interact with gcs and azure blob store correctly

### ISSUE THREAD

**Issue by nlu90** [streamnative/pulsar-io-cloud-storage#45]
**Describe the bug**
Currently the connector lack verification of running with
- [ ] gcs
- [ ] azure blob store

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by alpreu** [comment]
Closing this because it is confirmed to be working now

**Comment by freeznet** [comment]
@alpreu the gcs is working, but havnt done any implementation and tests with Azure yet.

**Comment by alpreu** [comment]
> @alpreu the gcs is working, but havnt done any implementation and tests with Azure yet.

I have opened a follow-up ticket for Azure here #467
